### ISSUE TITLE
Auth codes don't work

### ISSUE THREAD

**Issue by jackhadrill** [Zibbp/Radium#11]
When trying to authenticate as an admin using the `/auth {code}` chat command, an "Incorrect Code" error is returned and no priviledges are assigned.

This behaviour has been seen across multiple browsers and seems to occur for both the randomly generated auth codes, as well as a user-provided auth code.

**Comment by Zibbp** [comment]
I can't seem to replicate the error you are receiving. Are you omitting the `{ }` when entering the code in chat?
![Auth Example](https://i.ibb.co/tLhmTV8/image.png)

**Comment by jackhadrill** [comment]
I am indeed.

I'm launching the Docker container with the following command:
```bash
docker run --name=radium -p 3000:3000 -e BASE_URL=http://example.domain -e ADMIN_TOKEN=12345 zibbp/radium:latest
```
And then authenticating with `/auth 12345` as shown in your attached screenshot.

Having looked at the browser console, it appears that you try to connect to the websocket over port 80 which will not work because of both CORS and because I'm running this on port 3000.

![image](https://user-images.githubusercontent.com/1496537/92620610-bb64b680-f2ba-11ea-95c4-bb1e4dd349fb.png)


Hope this helps!

**Comment by Zibbp** [comment]
Ok, I was able to replicate the issue and I think I understand why this is happening.

If not using a reverse proxy to serve Radium, the port being used needs to be included in the BASE_URL.
```
-e BASE_URL=http://1.2.3.4:3000
```
This is a design flaw and I will either update the documentation or ensure if an IP is supplied rather than a domain it will use the port as well.

Another issue that you may face is the auth code starts with a number. I fixed this in the development branch awhile ago but was holding out on pushing the change until I made some more changes. Instead I will push out that change now which will allow you to use authentication codes that start with a number.

**Comment by jackhadrill** [comment]
Appreciate the quick investigation and resolution. Thanks for your help!

**Comment by Zibbp** [comment]
Just released [v1.1.9](https://github.com/Zibbp/Radium/releases/tag/v1.1.9) and is pushed to dockerhub.

If you are still having issues, feel free to reopen the issue.

**Comment by jackhadrill** [comment]
Changes made in v1.1.9 have introduced new issues. Please see console output below.

```bash
docker run --name=radium -p 3000:3000 -e BASE_URL=http://example.domain:3000 -e ADMIN_TOKEN=12345 zibbp/radium:latest

> Radium@1.1.9 start /opt/app
> nuxt start


 ERROR  ServerMiddleware Error: Cannot find module './routes/test'
Require stack:
- /opt/app/api/index.js
- /opt/app/node_modules/@nuxt/core/dist/core.js
- /opt/app/node_modules/@nuxt/cli/dist/cli-index.js
- /opt/app/node_modules/@nuxt/cli/dist/cli.js
- /opt/app/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module './routes/test'
  Require stack:
  - api/index.js
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-index.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Object.<anonymous> (api/index.js:8:14)
  at Generator.next (<anonymous>)

```

**Comment by Zibbp** [comment]
Pushed another update [v1.1.10](https://github.com/Zibbp/Radium/releases/tag/v1.1.10)  fixing that error. I had forgot to remove the import for the test route

I should set up automatic testing so situations like this don't happen again.

Sorry about this.
