### ISSUE TITLE
[Error] Startup fails due to bad response from 7TV API

### ISSUE THREAD

**Issue by waddyhussain** [Zibbp/Radium#65]
As of a few days ago, the docker image always fails to start, displaying the following error message:

```
Fetching 7TV emotes...

 FATAL  Request failed with status code 410


   ~U~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~U
   ~T~B                                         ~T~B
   ~T~B   ~\~V Nuxt Fatal Error                    ~T~B
   ~T~B                                         ~T~B
   ~T~B   Request failed with status code 410   ~T~B
   ~T~B                                         ~T~B
   ~U~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~T~@~U
```

The API route used for 7TV (https://api.7tv.app/v2/emotes/global) gives the following response
```
{
  "status_code": 410,
  "status": "Gone",
  "error": "Unknown Route",
  "error_code": 70498,
  "details": {
    "message": "The API endpoint requested does not exist"
  }
}
```

I couldn't find anything about this version of the API online, so I'm not sure if this is due to it being deprecated, or something else. I found a [v3 API](https://7tv.io/docs), but it doesn't seem to be fully implemented at the moment.

**Comment by waddyhussain** [comment]
Created a pull request #66

**Comment by Zibbp** [comment]
Hi,
Thanks for the PR, I've merged this. I don't personally use this application anymore so I'm not going to look into actually fixing the issue.

I've published a new release with this PR.

**Comment by waddyhussain** [comment]
Thanks for merging. It seems the docker image was updated for the `master` branch, but not the `next` branch. I'm not sure how GitHub actions works, but it's saying it failed the build. If you get a chance to look at it I'd appreciate it, but for now I've built the image locally so no worries if you don't have the time.

**Comment by Zibbp** [comment]
`next` should be pushed to the repository.

**Comment by waddyhussain** [comment]
Great thanks
