### ISSUE TITLE
Invalid administrator verification

### ISSUE THREAD

**Issue by xiya233** [Zibbp/Radium#8]
Users only need to enter /auth in the chat window to become an administrator

Please fix it, thanks

**Comment by Zibbp** [comment]
Thanks for pointing this out.

Just pushed update `1.1.8` that fixes this.

**Comment by xiya233** [comment]
Thank you for fixing it. There may still be a bug:

A password with a number in the first place will cause authentication to fail

**Comment by Zibbp** [comment]
Fixed in develop commit [#38a1d29](https://github.com/Zibbp/Radium/commit/38a1d29ae08450939dfe0bcddc4b3ef5affa3105)

It was happening because the user set token wasn't being converted to a string while the randomly generated one was.

I will merge develop into the master branch later today.
